### PR TITLE
Fix bug with checkbox max value

### PR DESCRIPTION
**Pull request by josmen**
Just fixing the bug where it would allow you to have max of 26 when the box was UNchecked, rather than when the box was checked. When it was unchecked with a max of 26 the program would loop infinitely since it couldn't find enough unique characters without sheik.

### CODE REVIEW

**Review by snapish — APPROVED** [review]

**Comment by snapish** [comment]
Brand new to GitHub. I was just looking at this and realized i had stuff
backwards. Thanks man! I think I committed it, pretty sure :P

**Comment by josmen** [comment]
It's approved, now there should be a button to merge pull request since I don't have write access. Should be at the bottom of the pull request page :) Keep on making dope stuff man!

**Comment by snapish** [comment]
Alright i believe it worked, you got any other ideas that could be thrown
in there? Open to suggestions/improvements :D

**Comment by josmen** [comment]
Depends on what you want to learn, if you are into web dev, then maybe try
to customize the look of the website, make it prettier etc.
But honestly it serves its purpose well, good job :)
I might make the split sheik and zelda button checked by default,
especially since that would take care of a bug where right now the checkbox
doesn't remove the option for 26 until it has been checked and unchecked
haha.
But good job, melee always needs more content creators from the programming
world, keep it up!

**Comment by snapish** [comment]
Yeah i can maybe mess around with the CSS some more. I was working on
trying to get the 26 to go away if the buttons checked. Rubber ducking to
you i just realized you could put that in the event listener, something
like if its at 26 and the button gets checked set it to 25. Think all thats
gatta happen for default checked is to add "selected" into the checkbox
element right?

**Comment by josmen** [comment]
Yup, put the word "checked" (no quotes) right after the type = "checkbox",
and it will be checked by default.

**Comment by snapish** [comment]
https://youtu.be/vzkiE_oSopM?t=36s

**Pull request merged**
